import type { ModalState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: ModalState, fileName = "modals"): ExportPayload {
  return { fileName: `${fileName || "modals"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: ModalState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "export default function ModalComponent({ open, defaultOpen = state.defaultOpen ?? state.previewState === \"open\", onOpenChange } = {}) {",
    "  const isControlled = open !== undefined;",
    "  const [internalOpen, setInternalOpen] = React.useState(defaultOpen);",
    "  const isOpen = isControlled ? open : internalOpen;",
    "  const triggerRef = React.useRef(null);",
    "  const titleId = `${state.id}-title`;",
    "  const descriptionId = `${state.id}-description`;",
    "  const setOpen = React.useCallback((nextOpen) => {",
    "    if (!isControlled) setInternalOpen(nextOpen);",
    "    onOpenChange?.(nextOpen);",
    "    if (!nextOpen && state.focusReturn) requestAnimationFrame(() => triggerRef.current?.focus());",
    "  }, [isControlled, onOpenChange]);",
    "  React.useEffect(() => {",
    "    if (!isOpen || !state.closeOnEscape) return;",
    "    const onKeyDown = (event) => { if (event.key === \"Escape\") setOpen(false); };",
    "    document.addEventListener(\"keydown\", onKeyDown);",
    "    return () => document.removeEventListener(\"keydown\", onKeyDown);",
    "  }, [isOpen, setOpen]);",
    "  const placement = state.placement || \"center\";",
    "  const panelStyle = {",
    "    width: state.width,",
    "    maxWidth: \"calc(100vw - 24px)\",",
    "    maxHeight: \"calc(100vh - 48px)\",",
    "    overflowY: state.scrollable ? \"auto\" : \"visible\",",
    "    padding: state.padding,",
    "    display: \"grid\",",
    "    gap: state.gap,",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px solid ${state.border}`,",
    "    boxShadow: `0 ${Math.round(state.shadow / 3)}px ${state.shadow}px rgba(0,0,0,.28)`,",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: state.fontFamily,",
    "    transition: state.motion ? \"opacity 0.2s ease, transform 0.2s ease\" : \"none\",",
    "  };",
    "  const overlayStyle = {",
    "    position: \"fixed\",",
    "    inset: 0,",
    "    zIndex: 40,",
    "    display: \"grid\",",
    "    placeItems: placement === \"center\" ? \"center\" : placement === \"top\" ? \"start center\" : \"end center\",",
    "    padding: 24,",
    "    background: state.showOverlay ? \"rgba(15, 23, 42, .58)\" : \"transparent\",",
    "    transition: state.motion ? \"background 0.2s ease\" : \"none\",",
    "  };",
    "  return (",
    "    <div id={state.id}>",
    "      <button ref={triggerRef} type=\"button\" disabled={state.disabled} onClick={() => setOpen(true)}>",
    "        {state.triggerLabel || \"Open modal\"}",
    "      </button>",
    "      {isOpen && (",
    "        <div onMouseDown={(event) => { if (state.closeOnOutside && event.target === event.currentTarget) setOpen(false); }} style={overlayStyle}>",
    "          <section role=\"dialog\" aria-modal={state.modal} aria-label={state.ariaLabel} aria-labelledby={titleId} aria-describedby={descriptionId} tabIndex={state.tabIndex} style={panelStyle}>",
    "            <button type=\"button\" aria-label=\"Close modal\" onClick={() => setOpen(false)} style={{ justifySelf: \"end\" }}>Close</button>",
    "            <h2 id={titleId} style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "            <p id={descriptionId} style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "            <div style={{ display: \"flex\", flexDirection: state.actionLayout === \"column\" ? \"column\" : \"row\", gap: 8 }}><button type=\"button\">{state.label}</button><button type=\"button\">Cancel</button></div>",
    "            <p style={{ margin: 0, color: state.muted, fontSize: 12 }}>{state.helper} Focus trap is not implemented; focus return is {state.focusReturn ? \"enabled\" : \"disabled\"}.</p>",
    "          </section>",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
  ].join("\n");
}
