import type { ModalState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: ModalState, fileName = "modals"): ExportPayload {
  return { fileName: `${fileName || "modals"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: ModalState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
  "",
  "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
  "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "export default function ModalComponent({ open, defaultOpen = state.defaultOpen ?? state.previewState === \"open\", onOpenChange } = {}) {",
    "  const isControlled = open !== undefined;",
    "  const [internalOpen, setInternalOpen] = React.useState(defaultOpen);",
    "  const isOpen = isControlled ? open : internalOpen;",
    "  const triggerRef = React.useRef(null);",
    "  const titleId = `${state.id}-title`;",
    "  const descriptionId = `${state.id}-description`;",
    "  const setOpen = React.useCallback((nextOpen) => {",
    "    if (!isControlled) setInternalOpen(nextOpen);",
    "    onOpenChange?.(nextOpen);",
    "    if (!nextOpen && state.focusReturn) requestAnimationFrame(() => triggerRef.current?.focus());",
    "  }, [isControlled, onOpenChange]);",
    "  React.useEffect(() => {",
    "    if (!isOpen || !state.closeOnEscape) return;",
    "    const onKeyDown = (event) => { if (event.key === \"Escape\") setOpen(false); };",
    "    document.addEventListener(\"keydown\", onKeyDown);",
    "    return () => document.removeEventListener(\"keydown\", onKeyDown);",
    "  }, [isOpen, setOpen]);",
    "  const placement = state.placement || \"center\";",
    "  const [closeHover, setCloseHover] = React.useState(false);",
    "  const [primaryHover, setPrimaryHover] = React.useState(false);",
    "  const variantWidth = { sm: 420, md: 560, lg: 720, xl: 920, full: \"calc(100vw - 48px)\" };",
    "  const animationName = { fade: \"modalFade\", scale: \"modalScale\", \"slide-up\": \"modalSlideUp\", \"slide-down\": \"modalSlideDown\" };",
    "  const overlayAlpha = Math.round(Math.max(0, Math.min(1, state.overlayOpacity)) * 255).toString(16).padStart(2, \"0\");",
    "  const panelStyle = {",
    "    width: state.width,",
    "    maxWidth: variantWidth[state.widthVariant] || \"calc(100vw - 48px)\",",
    "    maxHeight: state.maxHeight,",
    "    overflowY: state.scrollable ? \"auto\" : \"visible\",",
    "    display: \"grid\",",
    "    gridTemplateRows: \"auto 1fr auto\",",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px ${state.borderStyle} ${state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border}`,",
    "        boxShadow: buildShadow(state),",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: resolveFont(state),",
    "    overflow: \"hidden\",",
    "    opacity: state.disabled ? (state.disabledOpacity ?? 0.5) : 1,",
    "    cursor: state.disabled ? state.disabledCursor : undefined,",
    "    animation: state.transitionDuration > 0 ? `${animationName[state.animationType] || \"modalScale\"} ${state.transitionDuration}ms ease` : undefined,",
    "  };",
    "  const overlayStyle = {",
    "    position: \"fixed\",",
    "    inset: 0,",
    "    zIndex: 40,",
    "    display: \"grid\",",
    "    placeItems: placement === \"center\" ? \"center\" : placement === \"top\" ? \"start center\" : \"end center\",",
    "    padding: 24,",
    "    background: state.showOverlay ? state.overlayBg + overlayAlpha : \"transparent\",",
    "    transition: state.transitionDuration > 0 ? \"background 0.2s ease\" : \"none\",",
    "  };",
    "  return (",
    "    <div id={state.id}>",
    "      <button ref={triggerRef} type=\"button\" disabled={state.disabled} onClick={() => setOpen(true)}>",
    "        {state.triggerLabel || \"Open modal\"}",
    "      </button>",
    "      {isOpen && (",
    "        <div onMouseDown={(event) => { if (state.closeOnOutside && event.target === event.currentTarget) setOpen(false); }} style={overlayStyle}>",
    "          <style>{`@keyframes modalFade{from{opacity:0}to{opacity:1}}@keyframes modalScale{from{opacity:0;transform:scale(0.94)}to{opacity:1;transform:scale(1)}}@keyframes modalSlideUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}@keyframes modalSlideDown{from{opacity:0;transform:translateY(-16px)}to{opacity:1;transform:translateY(0)}}`}</style>",
    "          <section role=\"dialog\" aria-modal={state.modal} aria-label={state.ariaLabel} aria-labelledby={titleId} aria-describedby={descriptionId} tabIndex={state.tabIndex} style={panelStyle}>",
    "            <header style={{ display: \"flex\", alignItems: \"center\", justifyContent: \"space-between\", padding: state.padding, background: state.headerBg, color: state.headerText, borderBottom: `1px solid ${state.headerBorder}` }}>",
    "              <h2 id={titleId} style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "              <button type=\"button\" aria-label=\"Close modal\" onClick={() => setOpen(false)} onMouseEnter={() => setCloseHover(true)} onMouseLeave={() => setCloseHover(false)} style={{ display: \"grid\", placeItems: \"center\", width: state.closeIconSize + 16, height: state.closeIconSize + 16, border: 0, borderRadius: 999, background: closeHover ? state.closeIconHoverBg : \"transparent\", color: state.closeIconColor, cursor: \"pointer\" }}>",
    "                <svg aria-hidden=\"true\" width={state.closeIconSize} height={state.closeIconSize} viewBox=\"0 0 16 16\" fill=\"none\"><path d=\"M4 4l8 8M12 4l-8 8\" stroke=\"currentColor\" strokeWidth=\"1.6\" strokeLinecap=\"round\" /></svg>",
    "              </button>",
    "            </header>",
    "            <div style={{ padding: state.padding, display: \"grid\", gap: state.gap }}>",
    "              <p id={descriptionId} style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "              <div style={{ height: 1, background: state.dividerColor }} />",
    "              <p style={{ margin: 0, color: state.muted, fontSize: 12 }}>{state.helper} Focus trap is not implemented; focus return is {state.focusReturn ? \"enabled\" : \"disabled\"}.</p>",
    "            </div>",
    "            <footer style={{ display: \"flex\", flexDirection: state.actionLayout === \"column\" ? \"column\" : \"row\", justifyContent: \"flex-end\", gap: 8, padding: state.padding, background: state.footerBg, borderTop: `1px solid ${state.footerBorder}` }}>",
    "              <button type=\"button\" onMouseEnter={() => setPrimaryHover(true)} onMouseLeave={() => setPrimaryHover(false)} style={{ borderRadius: 12, padding: \"8px 16px\", border: 0, background: primaryHover ? state.primaryHoverBg : state.primaryBg, color: state.primaryText, cursor: \"pointer\" }}>{state.label}</button>",
    "              <button type=\"button\" style={{ borderRadius: 12, padding: \"8px 16px\", background: state.secondaryBg, color: state.secondaryText, border: `1px solid ${state.secondaryBorder}`, cursor: \"pointer\" }}>Cancel</button>",
    "            </footer>",
    "          </section>",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
  ].join("\n");
}
